name: Run Build
on: 
  pull_request:
      branches:
        - main

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Install
        run: npm install
      - name: Build
        run: gulp test