name: Compile Core
on: 
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build-deploy:
    name: Compile Core
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Install
        run: npm install
      - name: Compile + Commit
        run: |
          gulp compile
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Compile utilities"
      - name: Push changes
        uses: ad-m/github-push-action@0fafdd62b84042d49ec0cb92d9cac7f7ce4ec79e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
